### ISSUE TITLE
Question on rows

### ISSUE THREAD

**Issue by willmkt** [64robots/nova-fields#10]
Since nova-rows has been merged in this package, can we use:

Row::make('Lines', []) to make grid like forms?

Thanks.

**Comment by willmkt** [comment]
I want to use grid layouts in nova, it would be cool to use:

Row::make( [
      Number::make('Quantity')
        ->fieldClasses('w-full px-8 py-6')
        ->hideLabelInForms(),
      Text::make('Product')
        ->fieldClasses('w-full px-8 py-6')
        ->hideLabelInForms(),
]) 

to make a custom grid layout in any nova form, and use it with any fields.

Thanks.

**Comment by disitec** [comment]
Try to use fieldClasses.

```php
Row::make('Name', [
    Text::make('Text'),
    Textarea::make('Textarea'),
])->fieldClasses('flex')
```
