### ISSUE TITLE
Configurable conflict with Macroable

### ISSUE THREAD

**Issue by pehbehbeh** [64robots/nova-fields#104]
The `Field` parent class of all Nova fields has the `Macroable` trait wich uses a magic `__call` method. This package overwrites the `__call` method via the `Configurable` class to...

> Dynamically add or remove classes.

This breaks all Macros on all fields add we rely quite heavily on them. So the newest version is 
basically unusable for us.

This took quite some time to get behind... 😄 

Can you think of another way to add classes or do you have an idea to fix this behaviour?

**Comment by pehbehbeh** [comment]
A quick fix for me was to change [this line](https://github.com/64robots/nova-fields/blob/d3aa620bd924a98fa1f722393115cbfabfca45b4/src/Configurable.php#L395) to:

```php
            return parent::__call($method, $parameters);
```

What do you think?

**Comment by disitec** [comment]
Hey! Sorry about that!

Can you provide an example so I can reproduce it in my local and try to give the best of the both worlds?

Thanks 👍

**Comment by disitec** [comment]
Fixed that in 0.8.9.

Thanks for the catch ;)

**Comment by pehbehbeh** [comment]
Thanks!
