### ISSUE TITLE
Casting DateTime Fields Inside JSON

### ISSUE THREAD

**Issue by nickpoulos** [64robots/nova-fields#106]
This bug is an Extension of #52.  Using a DateTime field inside a JSON field causes the error "DateTime field must cast to 'datetime' in Eloquent model", with no way to work around it via casts. 

I submitted a PR which duplicates the solution from #52. Kind of ugly with the duplication but I could not think of another way without touching more of the repo.

**Comment by disitec** [comment]
Fixed in 0.10.1
