### ISSUE TITLE
Unable to store data using row field

### ISSUE THREAD

**Issue by mavericksthinker** [64robots/nova-fields#109]
Hello @disitec, I have been trying to use Row field to store data into DB 
```
            BelongsTo::make('Area')
                ->hideWhenUpdating(),
            
            Row::make('Area Languages', [
                Text::make('Area name')
                    ->fieldClasses('w-full px-8 py-6'),
                
                Select::make('Language','language_id')->options(config('locale'))
                    ->hideWhenUpdating()
                    ->default(2),
            ])->childConfig([
                'hideLabelInForms' => true,
            ]),
```
but while submitting I get the following error
```
exception: "Illuminate\Database\QueryException"
file: "/Users/bishalsahoo/Devs/Projects/Nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 664
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'area_languages' in 'field list' (SQL: insert into `area_languages` (`area_id`, `area_languages`, `updated_at`, `created_at`) values (1, [{"area_name":"asdda","language_id":"1","row_id":"vcxohpkp1"}], 2019-07-04 14:06:34, 2019-07-04 14:06:34))"
trace: [{,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…},…]
```
Just wondering, am I missing anything?
Any help will be deeply appreciated.

**Comment by gaabora** [comment]
Do you really have `area_languages` column in your `area_languages` table?

**Comment by mavericksthinker** [comment]
Thats the thing I am missing as ```area_languages =[{"area_name":"asdda","language_id":"1","row_id":"vcxohpkp1"}]``` based on this  ```Row::make('Area Languages', ``` Then the problem that I am facing is to store area_name,language_id into the area-languages table

**Comment by gaabora** [comment]
That is not how this particular field (Row) works. It stores a serialized JSON in selected field.
What you need is a relation, that you can attach on details page of a resource (not in edit form)

**Comment by mavericksthinker** [comment]
Thank you so much for the explanation and it makes sense now.

**Comment by disitec** [comment]
@mavericksthinker you can use the fillUsing method in the row field. Unset it in the model and then store the value in your related table.

```
->fillUsing(function($request, $model, $attribute, $requestAttribute) {
    unset($model->area_languages);

    // use $request->area_languages to perform extra logic.
});```

**Comment by mavericksthinker** [comment]
@disitec. Thats what was missing, thank you so much
