### ISSUE TITLE
Error with relationships and rows

### ISSUE THREAD

**Issue by bnowacky** [64robots/nova-fields#11]
using repeatable rows to save to a JSON field in a db. Getting this error: 

```
   Undefined property: R64\NovaRow\Row::$resourceClass
   {"userId":1,"email":"******@gmail.com","exception":"[object] 
   (ErrorException(code: 0): Undefined property: R64\\NovaRow\\Row::$resourceClass
   at /home/vagrant/code/project/nova/src/Http/Controllers/AssociatableController.php:23)
```

aded package with: `use R64\NovaRow\Row;`,  and this is the usage: 

```
     Row::make('Questions', [
                BelongsTo::make('Questions', 'questions', Question::class)
                    ->sortable()
                    ->hideFromIndex(),
            ])
```

Any idea what I'm missing here? The BelongsTo field works fine without the wrapper, but won't work with it.

**Comment by bnowacky** [comment]
Still seeing the same issue after updating to the latest release. Using the same implementation as discussed previously. 

![screen shot 2018-10-01 at 8 29 05 am](https://user-images.githubusercontent.com/1836896/46298693-8c812a00-c554-11e8-9e6c-3e0950d70a6e.png)

**Comment by disitec** [comment]
Are you using `R64\NovaFields\BelongsTo` in the child? The fix is done in the relation

**Comment by bnowacky** [comment]
Yes, using both: 
```
    use R64\NovaFields\Row;
    use R64\NovaFields\BelongsTo;
```

and in fields():
```
    Row::make('Questions', [
       BelongsTo::make('Questions', 'questions', Question::class)
            ->sortable()
            ->hideFromIndex(),
    ])
``` 

if I remove the Row:: and just use BelongsTo, it works with a single item (in this case question), but doesn't work with the Row. I also confirmed I have the latest updates that were pushed in v.0.2.9

**Comment by disitec** [comment]
what version of nova do you have?

**Comment by bnowacky** [comment]
Tried both v1.0.16 and just updated to 1.1.4, same error.

**Comment by disitec** [comment]
Sorry I cant reproduce this in the last version of nova. Can you remove vendor directory and composer.lock file and do a fresh composer install?

**Comment by bnowacky** [comment]
No luck. Happens as soon as I click "add row". I am also using another nova package, `fourstacks/nova-repeatable-fields`. Not using it on the same page, but any chance there's some conflict or something between the two? 

Any other ideas to look out for? I know not much you can do without being able to repro, but this is literally the last piece I have for a project. 

Really appreciate the help !

**Comment by disitec** [comment]
Sorry again. I tried hard to reproduce the issue but I cant. Please provide a reproduction and I will be happy to help you with
