### ISSUE TITLE
Float keys not stored in JSON field

### ISSUE THREAD

**Issue by techouse** [64robots/nova-fields#110]
I wanted to use float keys in as my field names like so:

```php
JSON::make(
    __('Preferences'),
    [
        Text::make("Article 1", "1"), // <-- gets saved
        Text::make("Article 2", "2"), // <-- gets saved
        Text::make("Article 2.1", "2.1"), // <-- does not get saved
        Text::make("Article 44.2", "44.2"), // <-- does not get saved
    ],
    'preferences'
),
```

All float keys do not event make it into the json and it ends looking like this:

```json
{
    "1": "blabla 1", 
    "2": "blabla 2"
}
```

However if I replace the `.` in the float for a `_` it works, like so:

```php
JSON::make(
    __('Preferences'),
    [
        Text::make("Article 1", "1"), // <-- gets saved
        Text::make("Article 2", "2"), // <-- gets saved
        Text::make("Article 2.1", "2_1"), // <-- gets saved
        Text::make("Article 44.2", "44_2"), // <-- gets saved
    ],
    'preferences'
),
```

This time it gets saved as:

```json
{
    "1": "blabla 1", 
    "2": "blabla 2",
    "2_1": "blabla 2_1",
    "44_2": "blabla 44_2"
}
```

**Comment by gaabora** [comment]
It maybe fixable on server side, cause from client sends valid data. You may need to do somthing with this line.
https://github.com/64robots/nova-fields/blob/41805e6244b69e29d7753da1ad63d4007072bbcf/src/JSON.php#L156
But in case that dot used to sepatate calculatable or nested attributes I do not think this wold be solvable

**Comment by techouse** [comment]
I tried fiddling with that line already but it got me nowhere. 😢
