### ISSUE TITLE
Make compatible with latest laravel nova version (v2.1.0)

### ISSUE THREAD

**Issue by ArmeniaH** [64robots/nova-fields#114]
Hey there

Laravel nova got an update and they have changed some stuff related to fields
For example 
```public function showOnIndex()``` 
on the fieldchanged to 
```public function showOnIndex($callback = true)``` 
and that's why multiple errors are ocurring because of the compatability.

**Comment by robmpreston** [comment]
Thanks, we'll take a look and get it updated.

**Comment by disitec** [comment]
Just released `0.11.0` compatible with Nova 2.1.0 🎉

**Comment by ArmeniaH** [comment]
Wow this was fast !!!!

Thanks alot
