### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by thebluebug** [64robots/nova-fields#118]
Hello, I'm getting the following JS error when trying to create/update. The create/update button won't let me submit. Here's the JS error:

```
TypeError: Cannot read property 'status' of undefined
    at p.<anonymous> (app.js?id=b8265367338097693595:formatted:13231)
    at y (app.js?id=b8265367338097693595:formatted:16860)
    at Generator._invoke (app.js?id=b8265367338097693595:formatted:16838)
    at Generator.e.<computed> [as next] (app.js?id=b8265367338097693595:formatted:16875)
    at o (app.js?id=b8265367338097693595:formatted:22898)
    at app.js?id=b8265367338097693595:formatted:22910
    at new Promise (<anonymous>)
    at new t (app.js?id=b8265367338097693595:formatted:25246)
    at p.<anonymous> (app.js?id=b8265367338097693595:formatted:22895)
    at p.<anonymous> (app.js?id=b8265367338097693595:formatted:13239)
It @ vendor.js?id=da751a53228a35fab7c4:formatted:39444

```
We need to wrap Flexible content (https://github.com/whitecube/nova-flexible-content v0.1.10) and a few other R64 fields inside this R64 JSON field for our data needs:
```
            JSON::make('Test', [
                Text::make('Test', 'test'),
                Text::make('Test 2', 'test2'),
                Flexible::make('Test', 'test')
                    ->button('Test')
                    ->addLayout('Test', 'test', [
                        Text::make('Test', 'test')
                        Text::make('Test 3', 'test3'),
                        Text::make('Test 4', 'test4'), 
            ], 'data'),
```

Whitecube nova-flexible-content v0.1.7 and below works.

**Comment by thebluebug** [comment]
I've been adding my discoveries here: https://github.com/whitecube/nova-flexible-content/issues/57
Still haven't resolved this if anyone has any clues how to register the fields properly...

**Comment by thebluebug** [comment]
@disitec 

Anyone? ... Bueller?

**Comment by disitec** [comment]
Hi @thebluebug you said that v0.1.7 works so I assume this is a bug related with the third party package? If you provide a clear direction to follow or a more detailed description of the issue feel free to reopen it!

Thank you

**Comment by thebluebug** [comment]
@disitec With versions of Whitecube nova-flexible-content above v0.1.7, they fixed field validation within their Flexible field. We need to use their latest to be able to validate any nested fields. We want to use R64 JSON field that wraps a Flexible field (with other fields inside that, Text, etc).

Desired payload example:
```
{
	"name": "Name",
	"price": "23",
	"total": "25",
	"discount": "8.00",
	"hero_image": "",
	"description": "",
	"mktg": "",
	"student_choices": [
		{
			"key": "1f68d81d3755fff1",
			"layout": "student_choice_selections",
			"attributes": {
				"title": "d",
				"products": "[{\"sku\":\"A000\",\"name\":\"Product Name\",\"price\":25,\"category\":\"Apparel\",\"vgt_id\":0,\"originalIndex\":0,\"vgtSelected\":true,\"upchargeActive\":false,\"upchargeAmount\":\"\"}]",
				"max_allowed": "1"
			}
		}
	],
	"short_description": "",
	"bundle_default_products": "[{\"sku\":\"A0009\",\"name\":\"Product Name 2\",\"price\":25,\"category\":\"Apparel\",\"vgt_id\":0,\"originalIndex\":0,\"vgtSelected\":true}]"
}
```

If you install the latest Whitecube Flexible Content with Nova Fields and use this simpler example of the code that I provided earlier in my original post, you'll see the error when you try to update/edit:
```
            JSON::make('Test', [
                Text::make('Test', 'test'),
                Text::make('Test 2', 'test2'),
                Flexible::make('Test', 'test')
                    ->button('Test')
                    ->addLayout('Test', 'test', [
                        Text::make('Test', 'test')
                        Text::make('Test 3', 'test3'),
                        Text::make('Test 4', 'test4'), 
            ], 'data'),
```

Hopefully that clarifies the problem.

**Comment by disitec** [comment]
I've been debugging this issue a bit more. The error is thrown by the flexible-content library exactly at this point
https://github.com/whitecube/nova-flexible-content/blob/master/resources/js/components/FormField.vue#L138

Json field formats as an object to be appended to the parent formData thats why that `has` method is not found.

I think they should be support Nova Fields in their package instead the other way around. Anyway let me know if we can help.

Thanks!

**Comment by thebluebug** [comment]
@disitec Thanks for taking the time to look into it! I know it fails at that point - I mentioned that here: https://github.com/whitecube/nova-flexible-content/issues/57

Okay, agreed. As a workaround, we wound up locking to the version of Flexible that worked for us (v0.1.7) and then did server-side validation to check the two required fields (a Text and Select field) wrapped within the Flexible field. It throws a Toasted error message if one or both fields are not filled out.
