### ISSUE TITLE
Textarea rows attribute

### ISSUE THREAD

**Issue by OliverZiegler** [64robots/nova-fields#124]
It seems like the default Nova Textfield added option to define the `textarea` `rows` property.

Further more when you check the vue implementation it will also bind all the extraAttributes.
This feature seems missing here unfortunately...

The `v-bind="extraAttributes"` does the trick here...

**Nova Textarea**
```
<textarea
                class="w-full form-control form-input form-input-bordered py-3 h-auto"
                :id="field.attribute"
                :dusk="field.attribute"
                v-model="value"
                v-bind="extraAttributes"
            />
```

**64Robots Textarea**
```
<textarea
        :data-testid="field.attribute"
        :dusk="field.attribute"
        :disabled="readOnly"
        type="text"
        v-model="value"
        :class="[errorClasses, inputClasses]"
        :placeholder="placeholder"
      />
```

**Comment by disitec** [comment]
Added support to extraAttributes and rows in `0.11.2`
