### ISSUE TITLE
Grammar::parameterize() must be of the type array, string given

### ISSUE THREAD

**Issue by khalil-htme** [64robots/nova-fields#128]
All the fields work including JSON, but for some reason when using ROW i get the following error, "Only on create" on update it works perfectly, but on create it breaks everything.

**Steps to produce:**
1) Make a blank model/resource
2) add the following code: (Taken from docs)

       public function fields(Request $request)
       {
            return [
                     ID::make()->sortable()->hideFromDetail(),
                     Row::make('Lines', [
                       Number::make('Quantity')
                         ->fieldClasses('w-full px-8 py-6')
                         ->hideLabelInForms(),
                       Text::make('Product')
                         ->fieldClasses('w-full px-8 py-6')
                         ->hideLabelInForms(),
                       Number::make('Price')
                         ->fieldClasses('w-full px-8 py-6')
                         ->hideLabelInForms(),
                     ])->nullable(),
                 ];
        }

3) MY DB field:

            public function up()
                {
                    Schema::create('material_requests', function (Blueprint $table) {
                        $table->bigIncrements('id');
                        $table->json('lines')->nullable();
                        $table->timestamps();
                    });
                }

any advice on what to do please?

**ERROR:**

{,…}
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/home2/htms/laravel/vendor/laravel/framework/src/Illuminate/Database/Grammar.php"
line: 136
message: "Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in /home2/htms/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 869"
trace: [{,…}, {function: "Illuminate\Database\Query\Grammars\{closure}",…},…]

**Comment by disitec** [comment]
As your field is a `json` field you should `json_encode` the request. You can achieve that using `fillUsing` method

```
->fillUsing(function ($request, $model) {
    $model->lines = json_encode($request->lines);
})
```

We are adding this tip in the docs. 

Thanks for the report!

**Comment by khalil-htme** [comment]
amazing thanks!
