### ISSUE TITLE
[BUG] Nova 2.5.0 Required Rule issue

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-fields#133]
When updated to Nova 2.5.0, this fields fails to be handled properly as the new `isRequired` addition. This makes any form pages with this field on it unable to load.
The issue is the rules are generated like:

    array:4 [
      "name_extension." => []
      "name_extension.original" => []
      "name_extension.addition" => array:2 [
        0 => "nullable"
        1 => "max:50"
      ]
      "name_extension.condition" => []
    ]

instead of:

    array:4 [
      "name_extension" => []
      "name_extension.original" => []
      "name_extension.addition" => array:2 [
        0 => "nullable"
        1 => "max:50"
      ]
      "name_extension.condition" => []
    ]

This causes the new "required" check to fail with "undefined index" as it looks for `name_extension` and not `name_extension.`

The temporary fix I had, which I was going to submit as a PR asap, unless someone fixes it sooner is just checking the key like (L170 of JSON.php):
`return [$this->attribute . ($key ? '.' . $key : '') => $rules];`
so that the non-suffixed key exists as nova is expecting.

**Comment by dtannen** [comment]
@ragingdave for some reason Row field can't be used in Nova Actions.  Do you have a fix for that?
