### ISSUE TITLE
[BUG] Adding Row as a field in a nova action causes browser to hang

### ISSUE THREAD

**Issue by dtannen** [64robots/nova-fields#135]
Since Nova v2.4.0 -- using Row as a field in a Nova Action causes UI to hang. Probably related to inline actions.

**Comment by dtannen** [comment]
@disitec thanks!  I have a branch with all the custom action names, etc. and this bug is preventing me from merging it.

**Comment by disitec** [comment]
I dont know exactly what is causing this. But if i use a row field in the action, this modal is rendered infinite times. It starts to work if I comment the portal. 

`vendor/laravel/nova/resources/js/components/ActionSelector.vue`

![image](https://user-images.githubusercontent.com/12644599/67229399-87cb3480-f43b-11e9-9112-3f79badb6928.png)

**Comment by dtannen** [comment]
here is the code that is working in 2.3.1

`        
        <transition name="fade">
            <component
                :is="selectedAction.component"
                :working="working"
                v-if="confirmActionModalOpened"
                :selected-resources="selectedResources"
                :resource-name="resourceName"
                :action="selectedAction"
                :errors="errors"
                @confirm="executeAction"
                @close="closeConfirmationModal"
            />
        </transition>
        `

**Comment by disitec** [comment]
Row field uses a modal for delete row confirm. I think this may cause the issue. Rendering a portal inside a portal.

**Comment by disitec** [comment]
Fixed. Available in 0.13.0
