### ISSUE TITLE
Support for nested JSON

### ISSUE THREAD

**Issue by ibrunotome** [64robots/nova-fields#14]
Thank you for this package.

I'm trying to make a simple nested json like below and getting a "trying to get price of non-object". Can you add support for nested JSON?

<img width="283" alt="screenshot 2018-10-01 15 37 36" src="https://user-images.githubusercontent.com/4256471/46308511-392ccd00-c590-11e8-8873-8084dd5298d9.png">

**Comment by tanthammar** [comment]
Oh Yes, please :)

**Comment by disitec** [comment]
This feature is a bit tricky. Any of you have a path to follow in mind? Don't hesitate in send PRs. They dont have to be perfect :D

**Comment by simonfunk** [comment]
I've fixed it for now to make it work for nova-dependency-container:

`    protected function fillAttributeFromRequest(NovaRequest $request, $requestAttribute, $model, $attribute)
    {
        $this->fields->each(function ($field) use ($request, $model, $attribute) {
            if($field->component === 'nova-dependency-container') {
                collect($field->meta['fields'])->each(function ($field) use ($request, $model, $attribute) {
                    $field->fillInto($request, $model, $attribute . '->' . $field->attribute, $attribute . '.' . $field->attribute);
                });
            } else {
                $field->fillInto($request, $model, $attribute . '->' . $field->attribute, $attribute . '.' . $field->attribute);
            }
        });
    }`

But it needs more outwork for working with other components or more nested container. Also nested JSON need some more work. When i have time, i will try to work on it

**Comment by disitec** [comment]
That’s awesome. Thank you.

**Comment by Fabio1988** [comment]
I would also appreciate a nested JSON feature. This request is from last year, also #69 is mentioning the same issue :)

**Comment by ragingdave** [comment]
There seems to be some if just minimal support as I have a JSON field in a JSON field already and it's working as expected. This also includes some Panels thrown in which, aren't all that pretty and there is some field re-ordering that I'll be making an issue about, but it seems to be working

**Comment by disitec** [comment]
I’m closing this as it appears to be supported in newer versions.

**Comment by ragingdave** [comment]
Sorry to be the bearer of bad news.....but it seems I was mistaken and only testing half of it. When you actually try and update nested json fields, the saves never go all the way through...and depending on the nesting structure makes it so it may or may not work depending on the level of nesting (in my case 3 levels of nesting (top level model attribute is JSON, then `hours` as JSON key, which itself has JSON for  open/close properties).
