### ISSUE TITLE
delete icon not functional on File Field

### ISSUE THREAD

**Issue by dtannen** [64robots/nova-fields#145]
File::make('Form')
                          ->delete(function ($request, $model, $disk, $path) {
                              if (!$path) {
                                  return;
                              }
                              Storage::disk('disk')->delete($path);
                              $this->model->delete();

                              return [];
                          })
                          ->draggable()
                          ->disk('disk')
                          ->previewBeforeUpload()
                          ->addFieldClasses('w-full')

Click on the delete icon and nothing happens.

**Comment by dtannen** [comment]
@disitec is this broken for you?

**Comment by disitec** [comment]
Hey @dtannen Can I get a minimal reproduction without complex app logic to reproduce the error? Also it would be great if you can attach any console or network errors.

Thanks!

**Comment by dtannen** [comment]
@distec there is no network or console errors.  It doesn't seem like the dusk event is being captured for the delete button on file input.  Does the generic file input delete function work?

**Comment by disitec** [comment]
Are you having this issue on create or edit screen?

**Comment by dtannen** [comment]
@disitec edit

**Comment by disitec** [comment]
One more thing. Is the file on the root of the resource or inside a Row or Json field?

**Comment by dtannen** [comment]
@disitec the one I'm testing is not inside row or json

**Comment by disitec** [comment]
Fixed and working on `0.15.0` 🎉
