### ISSUE TITLE
Missing asterisk

### ISSUE THREAD

**Issue by OliverZiegler** [64robots/nova-fields#151]
As of Nova Version 2.5.0 (I think), when applying the `required` validation rule or adding a required callback function to the filed that returns `true, nova will automatically add a red asterisk behind field label.
This seems to be missing on each of the provided fields in this package.

Would be nice if could be added.

**Comment by gmooren** [comment]
As far as I can see my fix for #152 does also solve this problem.

**Comment by disitec** [comment]
Fixed in 0.16.0
