### ISSUE TITLE
Image field save filename to JSON field

### ISSUE THREAD

**Issue by 56degreesdesign** [64robots/nova-fields#154]
I would like the filename to be saved in JSON field after adding image file by Image field.
Now, if I add the Image field in the JSON field ,the name is saved outside of JSON in another field.

**Comment by disitec** [comment]
Can you provide reproduction steps sharing your code? Thanks

**Comment by disitec** [comment]
I'm going to close this due to inactivity. Feel free to reopen if you still having this issue!
