### ISSUE TITLE
Nested JSON with panels results in field re-ordering

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-fields#159]
For example:

    JSON::make('Extras', [
        new Panel('This should be first', [ <Fields> ]),
        Text:make('should be second'),
    ]),

This results in the the Text field displaying before the panel so the fields aren't maintaining the order given. This can also be confirmed via the ajax response that loads the configuration...It's correctly ordered there, but panels always seem to show last rather than in the order they were defined.
This might not seem like a big deal, but if you need the UI to display in a specific order this totally breaks that.

**Comment by ragingdave** [comment]
Disregard it seems to be resolved in a newer version than I had

**Comment by ragingdave** [comment]
Sorry for the spam, thought it was addressed, but it seems to still be an issue at least on the index page view specifically. It still is re-ordering fields/panels to always have the panels last.

**Comment by beliolfa** [comment]
Fix available on 0.17.0
