### ISSUE TITLE
Validation of JSON Fields

### ISSUE THREAD

**Issue by tjmartin69** [64robots/nova-fields#16]
Hi,

Seems like the JSON fields are not validated. Would be really great to support this.

Is this something you are planning to implement in the future?

Many Thanks,
Tom

**Comment by idragon81** [comment]
Really need this.

**Comment by idragon81** [comment]
Also, is it possible to add a validation rule on the JSON Field itself?
Doing something like 
` JSON::make('Others', [
                Date::make("Date", "dailyMenuDate")->resolveUsing(
                    function ($value) {
                        return Carbon::make($value)->format('Y-m-d');
                    })
            ], "meta")
                ->rules('required', new DailyMenuRule),
`
Works in a weird way, Create and Updates are prevented but not error message is shown

**Comment by disitec** [comment]
@idragon81 new issue opened here https://github.com/64robots/nova-fields/issues/19

**Comment by tjmartin69** [comment]
@disitec Maybe frontend validation on some rules would work. Let me have a dig into how validation is handled inside Nova I might be able to get a concept working. 

On a side note would it be possible to send the data as an array instead of json_encoded e.g. 
`config[message]=test` instead of `{"message":"test"}` this might make the validation work easier. And would stop us having to do ```
            $request->merge([
                $requestAttribute => json_decode($request[$requestAttribute], true)
            ]);```

**Comment by disitec** [comment]
Added support via PR #26
