### ISSUE TITLE
Regression: Nova view methods no longer working

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-fields#160]
Originally fixed in #7 I'm not sure what brought it back, but the meta isn't being returned appropriately for the frontend to hide the fields anymore. Based on reviewing the code changes from that issue, it seems the fix applied doesn't really solve the issue in the first place as it doesn't seem to handle propagating child field view states (onlyDetail as an example) through to the frontend. Note that this is specifically when using the JSON nova-fields from this package, but then using the standard Text/Number/etc fields directly available in Nova.

Upon testing, it seems that using the 64robots version of the Text field works to properly hide the field, but standard fields don't work. Additionally, the 64robots version of the Textarea doesn't hide either.

**Comment by beliolfa** [comment]
Hey @ragingdave! Thanks for reporting. I came up with a clean solution and removed all those unnecesseary re-declaration of view methods. Now im adding the extra meta needed in row in the construct.

This will be available on 0.17.0 🎉
