### ISSUE TITLE
Panels in JSON don't look like Panels

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-fields#161]
When using nesting of fields that are themselves in Panels. It would think that panels look like the panels that nova uses, but instead they end up just being sort of smooshed together fields with a heading instead of a panel type view on the detail page.

**Comment by beliolfa** [comment]
Sorry about the late replay. We were very busy lately with client work. Can you provide code examples or / and screenshots of what you are getting?

**Comment by beliolfa** [comment]
Fix available on 0.17.0
