### ISSUE TITLE
Resolve callbacks not called for Row

### ISSUE THREAD

**Issue by jbardnz** [64robots/nova-fields#163]
Hi there,

I am seeing the same issue that was previously fixed in #58. Calling a callback in a Row does not fire:

```
  Row::make('Order Items', [
    Text::make('Name'),
    Number::make('Amount', null, function($value){
        dd($value);
    }),
])->alwaysShow()->hideLabelInDetail()
```

Cheers

**Comment by percymamedy-wq** [comment]
Facing the same issue

**Comment by beliolfa** [comment]
Cannot reproduce with Nova 3.4.1 and Nova Fields 0.16.0.

Feel free to reopen it with detailed reproduction steps. Thanks!
