### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined on Row field

### ISSUE THREAD

**Issue by phuclh** [64robots/nova-fields#165]
I just updated to Nova 3.3.2 then I got this error on Row field.

<img width="1432" alt="Screen Shot 2020-04-12 at 8 15 12 AM" src="https://user-images.githubusercontent.com/6707194/79058265-ec9e7380-7c95-11ea-885d-e22c4f87e2ce.png">
<img width="1423" alt="Screen Shot 2020-04-12 at 8 15 20 AM" src="https://user-images.githubusercontent.com/6707194/79058266-f0ca9100-7c95-11ea-8438-e38fce08314d.png">

**Comment by ghuniyu** [comment]
same here on 3.2.0 and 3.4.0

![issue](https://user-images.githubusercontent.com/20877422/79699714-584a9700-82bb-11ea-9cc7-30dcda820574.png)

**Comment by beliolfa** [comment]
I can't reproduce this behavior using nova-fields 0.16.0 and nova 3.4.1

Can you share reproduction steps? Thanks!

**Comment by beliolfa** [comment]
I added a couple of extra checks for Row and Json field. Give it another try in 0.17.0

Thanks
