### ISSUE TITLE
Missing styling on Row field

### ISSUE THREAD

**Issue by jwktje** [64robots/nova-fields#171]
I'm using the row field but I think the styling is broken somehow. I can't figure out what's going wrong.

Here is my code;

```
Row::make('Table test', [
                Number::make('Number 1'),
                Number::make('Number 2'),
                Boolean::make('Boolean'),
]),
```

This is the result;
<img width="1034" alt="Screenshot 2020-06-09 at 12 36 18" src="https://user-images.githubusercontent.com/4722137/84138066-f9e59d80-aa4d-11ea-971e-8fadcd342e3a.png">

**Comment by jwktje** [comment]
I figured out how I can use the following config to style the rows; 
```
->childConfig([
                'fieldClasses' => 'w-full px-8 py-6',
                'wrapperClasses' => 'flex',
                'hideLabelInForms' => true,
            ])
```

This however doesn't get me to a table heading like in the docs. How do I achieve this?

<img width="475" alt="Screenshot 2020-06-09 at 12 59 54" src="https://user-images.githubusercontent.com/4722137/84139969-218a3500-aa51-11ea-9276-71e820451e51.png">

**Comment by beliolfa** [comment]
boolean check doesnt grow with the full width so the other two fields are taking all the space available. I recommend you to use `flex-1` instead.

```
->childConfig([
                'fieldClasses' => 'w-full px-8 py-6',
                'wrapperClasses' => 'flex-1',
                'hideLabelInForms' => true,
            ])
```


![image](https://user-images.githubusercontent.com/12644599/84190560-6d5fcd00-aa97-11ea-8f98-600191a1a954.png)
