### ISSUE TITLE
quickCreate with parameters to populate values not working

### ISSUE THREAD

**Issue by iamoat** [64robots/nova-fields#176]
I tried the following code but the value was not populated on the modal window.

![image](https://user-images.githubusercontent.com/1286835/85912107-368a0500-b854-11ea-9537-f634e33db692.png)

```
 BelongsTo::make('Billing Address', 'billing_addr', 'App\Nova\Address')
                ->hideFromIndex()
                ->quickCreate(['postal_code' => '11111'])
                ->labelClasses('w-1/5 px-8 py-6')
                ->fieldClasses('w-4/5 px-8 py-6')
                ->nullable()
                ->disableTrashed(),
```

![image](https://user-images.githubusercontent.com/1286835/85912150-8963bc80-b854-11ea-9a79-b7ec3c1f56e9.png)

**Comment by beliolfa** [comment]
Just released 0.18.0 with the fix. Thanks for reporting it! 🎉
