### ISSUE TITLE
quickCreate modal breaks if there are any fields forEach is not a function

### ISSUE THREAD

**Issue by eboye** [64robots/nova-fields#179]
When using the field like this:

`\R64\NovaFields\BelongsTo::make( 'Hotel' )->quickCreate()->disableTrashed(),`

it shows overlay for modal with loading animation but without the actual modal.

`Uncaught (in promise) TypeError: (intermediate value).forEach is not a function`

The actual Hotel model has some fields.

If I drop all the fields except ID field from that hotel model it gives me cancel, create, create and add new buttons without fields.

The XHR request I see for the hotel that scripts makes returns fields and panels, but it seems that the script is not catching it in forEach.

![image](https://user-images.githubusercontent.com/624357/88605516-69553200-d07a-11ea-8e6c-904d72562a18.png)

I believe that if breaks here by inspecting the js in debugger: https://github.com/64robots/nova-fields/blob/master/resources/js/modals/ModalCreate.vue#L116

I'm not sure why. I've tried forking it but haven't actually made package myself for laravel (only nova components etc.) so I'm not sure how I would use webpack in debug mode to test it out to log the data and hunt down the error.

Can anyone help?

PHP 7.4
Laravel 7.22.4
Nova 3.8.2
Nova Fields 0.17.0

**Comment by eboye** [comment]
Just a quick update. I was downgrading the nova version down until 3.0.* and it's where it started working. So something after that build version broke quickCreate.

**Comment by beliolfa** [comment]
Thanks for your detailed report. Definitely is something Nova has introduced that has broken this package. Will investigate and make a trace and see if I can find out where is the source of the issue.

**Comment by beliolfa** [comment]
Just released 0.18.0 with the fix. Thanks to pointing that out! 🎉

**Comment by eboye** [comment]
Great, thanks!

Well, I did as much as I could to debug :) It's much easier if you know what is broken and where to look at. If all my clients and colleges did thorough research before saying "it doesn't work" life would be much easier :D
