### ISSUE TITLE
Help Texts are not visible any more in JSON field

### ISSUE THREAD

**Issue by armeniax** [64robots/nova-fields#187]
Help texts are gone due to the following change

https://github.com/laravel/nova/commit/7fee1bc3eda064f1998ff0aa515d995c7513801b

They added something like :show-help-text="showHelpText" in default field view and other field views as well, seems like this is something needs to be implemented in JSON Form Field or Form Field Item.

**Comment by ArmeniaH** [comment]
Any news on this ?

**Comment by ArmeniaH** [comment]
Adding ```:show-help-text=true``` to the component template in ```FormFieldItem.vue``` fixes the issue, unfortunately, I don't have my computer with me to create pull request.

**Comment by beliolfa** [comment]
Thank you @ArmeniaH I've been a bit busy these days it would be awesome if you could do that PR. I'll be happy to review and merge!

**Comment by armeniax** [comment]
@beliolfa 
https://github.com/64robots/nova-fields/pull/199

**Comment by beliolfa** [comment]
Thank you! available on 0.21.0
