### ISSUE TITLE
Row field is not hydrated in form view (undefined error thrown in console)

### ISSUE THREAD

**Issue by malinowskip** [64robots/nova-fields#189]
It looks like the Row form field is not populated with existing data. I'm using Nova 3.19.1. Below is an error that appears when a form for a Row field is rendered.

![Screenshot from 2021-01-22 22-46-00](https://user-images.githubusercontent.com/47485431/105552389-1e079d80-5d04-11eb-9778-898f314a7d9d.png)

The error seems to be thrown in line 190 in `resources/js/components/row/FormField.vue` when the `handleChange` method is used. I have verified this by using a try/catch block. Any ideas why this is happening?

**Comment by malinowskip** [comment]
I made progress tracing the bug and found a solution (and the possible cause):

```vue
// resources/js/components/row/FormField.vue

const element = ref[0]
element.handleChange(value[key])
```

The code above is used in the `onMount()` lifecycle method in the Vue compoment in order to hydrate the HTML input with existing data (`element` is a plain div that wraps the input field). `handleChange` is an unrelated method that is defined elsewhere in the Vue component. It must have been used erroneously in this case.

I fixed the issue by changing `element.handleChange(value[key])` to `element.value = value[key]`. I'm not getting any console errors and form fields are populated as expected on each update/refresh.

**Comment by beliolfa** [comment]
Sounds great! Can you send a PR with the fix? I will be happy to review it.

Thank you!

**Comment by malinowskip** [comment]
Thanks for the reply, @beliolfa . I have submitted a PR.

There is another issue. When creating a new entry with some Row data, I'm getting the following errors:

```
Array to string conversion
There was a problem submitting the form. "Internal Server Error"
```

The errors are only thrown on create. Not on edit. I tested both with and without the change that I described above, so it seems unrelated.
