### ISSUE TITLE
Idea: custom panel item classes

### ISSUE THREAD

**Issue by pehbehbeh** [64robots/nova-fields#2]
Hey, thanks again for another amazing Nova package!

It would be really great to also be able to manipulate the panel classes of a field:

https://github.com/64robots/nova-fields/blob/070cd04b26582990324dd3004d8478460b900ebc/resources/js/components/PanelItem.vue#L5
https://github.com/64robots/nova-fields/blob/070cd04b26582990324dd3004d8478460b900ebc/resources/js/components/PanelItem.vue#L13

**Comment by disitec** [comment]
Sure. Will do 🤙🏻

**Comment by disitec** [comment]
Added two new methods `panelFieldClasses` and `panelLabelClasses` to 0.1.9  🎉
