### ISSUE TITLE
Image not working in Rows

### ISSUE THREAD

**Issue by remipou** [64robots/nova-fields#23]
The image url is always empty when i save my resource.
`images: "[{"image":"","caption":"test"}]"`
Here's the code in my resource class:
```			
Row::make('Images', [
	Image::make('image')
		->disk('public')
		->path('images')
		->hideLabelInforms()
		->fieldClasses('w-full px-8 py-6'),
	Text::make('caption')
		->hideLabelInforms()
		->fieldClasses('w-full px-8 py-6')
	])
->hideLabelInForms()
->fieldClasses('w-full px-8 py-6'),
```

**Comment by disitec** [comment]
At this moment Row field listen to the input changes in its subfields and create a new JSON that is sent to the server. We are not handiling image uploads in this subfields. Any suggestion on this?

**Comment by remipou** [comment]
nice work with these fields! i'll be happy to have a look.

**Comment by disitec** [comment]
Closing due to innactivity. Feel free to reopen if you figure out how to handle uploads directly in row fields.
