### ISSUE TITLE
Json field no update

### ISSUE THREAD

**Issue by iAxel** [64robots/nova-fields#27]
I use json field for role permissions but, I can't update... Maybe its my wrong?
In `Nova/Role`
```php
JSON::make('Permissions', [
    Boolean::make('view_admin'),
]),
```
In `Role`
```php
protected $casts = [
    'permissions' => 'array',
];
```
I change casts permissions to object but again dont work...

**Comment by iAxel** [comment]
Column type jsonb, in db column text (MariaDB)

**Comment by iAxel** [comment]
Okey, I used default boolean it's worked.

**Comment by guoxiangke** [comment]
has the same error. while update two json field.


`Json::make('name', [
                Text::make('en')
            ]),
            Json::make('description', [
                Text::make('en')
            ]),`

**Comment by iAxel** [comment]
> has the same error. while update two json field.
> 
> `Json::make('name', [ Text::make('en') ]), Json::make('description', [ Text::make('en') ]),`

Try default Boolean method
```php
Boolean::make('Create user', 'permissions->create-user')
    ->hideFromIndex()
    ->resolveUsing(function ($value) {
        return $value;
    }
),
```
