### ISSUE TITLE
row field validation

### ISSUE THREAD

**Issue by pehbehbeh** [64robots/nova-fields#30]
Hey, it seems that the sub fields of a row field are not validated. Are you planning to support this in the future?

We really need this, so we are thinking about  implementing it ourselves. Maybe we can contribute via PR if you like and did not already start an implementation. Are there any pitfalls you are already aware of?

Thanks for the great package!

**Comment by disitec** [comment]
Hey! That would be awesome! Please take a look into #26 This guy did an incredible work validating subdields in Json package. Maybe we could extract this to a trait or whatever. Thank you!

**Comment by PKuebler** [comment]
see #33

**Comment by sabid** [comment]
Hello @disitec 

 Can you see this error that i have on my form?. 

https://github.com/64robots/nova-fields/pull/33#issuecomment-433909893
