### ISSUE TITLE
Support for authorization on JSON subfields

### ISSUE THREAD

**Issue by pehbehbeh** [64robots/nova-fields#32]
I am trying authorization of JSON sub fields with something like this:

```php
JSON::make('HelloWorld, [
    Text::make('Example')
        ->canSeeWhen('seeExample', $this),
]),
```

But it does not seem to have any effect.

Can you think of a simple solution for this?

**Comment by pehbehbeh** [comment]
The more I think about our use-case... I think we have an extra challenge here:

Given user `A` can only access subfield `foo` and user `B` can only access subfield `bar` we also have to manage that nobody overwrites the whole JSON in the database with his own subset of data. 

And of course user B should not be able to see `foo` in the request (and vice-versa). So there needs to happen some kind of filtering.

**Comment by disitec** [comment]
Did you find some workaround for this? Would you make a PR?

**Comment by pehbehbeh** [comment]
Sorry, we haven't worked on this yet.

**Comment by disitec** [comment]
We don't have short-term plans for implementing this. Feel free to reopen this or submit a PR
