### ISSUE TITLE
How about addIndexClasses?

### ISSUE THREAD

**Issue by 949mac** [64robots/nova-fields#46]
I'm trying to add "whitespace-no-wrap text-left" to the Process column.

![image](https://user-images.githubusercontent.com/23151962/49191185-8330f580-f32a-11e8-970f-1caafee3e901.png)

Can you add a method to support something like this:

```
            BelongsTo::make('Process')
                ->addIndexClasses('whitespace-no-wrap text-left'),
```

Thanks!

**Comment by disitec** [comment]
Added `indexClasses()` and `addIndexClasses()` in 0.6.0
