### ISSUE TITLE
facing error when remove the dynamic row with nova row

### ISSUE THREAD

**Issue by yatin13490** [64robots/nova-fields#47]
hi,

when I remove the row it gives me an error of focus in the console. 

how to fix it ??
![ezgif com-crop](https://user-images.githubusercontent.com/6308981/49324702-3b43e580-f559-11e8-9d7b-6727c87016ac.gif)

**Comment by disitec** [comment]
Can you provide the error that are you getting? I can't reproduce this in my tests.

**Comment by emiliogrv** [comment]
@disitec Same error here, maybe the Row Component try focus some text field that not exists

**Comment by disitec** [comment]
Fixed in upcoming releas 0.6.2
