### ISSUE TITLE
field classess

### ISSUE THREAD

**Issue by 3309** [64robots/nova-fields#50]
Number::make('Quantity')
        ->fieldClasses('w-full px-8 py-6')
        ->hideLabelInForms(),

fieldClasses for Number does not exist? 
Having hard time in applying field and label classes? Please some documentation will be helpful.

**Comment by LocNguyen87** [comment]
You should use 
`R64\NovaFields\Number`
instead of 
`Laravel\Nova\Fields\Number`

**Comment by 3309** [comment]
Great. Working.  Are you planning to add other fields like Date?
Much appreciated.

**Comment by disitec** [comment]
Yeah. We want to support every native field in Nova. Only have to find time. Feel free to open a PR implementing whatever need you have.

Thanks!
