### ISSUE TITLE
Illegal string offset error when saving form

### ISSUE THREAD

**Issue by yabasha** [64robots/nova-fields#51]
Hello,

When I save or update a resource, I receive `illegal string offset` while I set 

$casts = [ 'contact' => 'object'];

Please advice,

**Comment by disitec** [comment]
Hey! Can you provide a reproduction?

**Comment by yabasha** [comment]
Hello,

I installed the `nova-field` library on a project with saved data in the database and the data was saved using `$casts = ['contact' => 'array']` 

When viewed the data using JSON custom field, it was displayed correctly but when save / update the records `illegal string offset` error was displayed.

After tracking the error, i found out that the saved record in database was serialized, so I cleared the db and everything works fine now creating / update records.

Thanx,
