### ISSUE TITLE
Using Row field with a json attribute breaks resolving of saved data.

### ISSUE THREAD

**Issue by jeffreydevreede** [64robots/nova-fields#53]
As you guys probably know, normally with a  nova text field in combination with a json attribute I can do the following:
**Works:** 
```php
// In model:
protected $casts = ['content' => 'array'];

// In resource:
Text::make('Example title', 'content->exampleTitle')
```

But when I am trying to do this in combination with the `Row` field it doesn't resolve the saved value, the rows I created are not being displayed, however the data seems to be as expected in the database.
**Broken:** 
```php
// In model:
protected $casts = ['content' => 'array'];

// In resource:
Row::make('USPs', [
    Text::make('Line'),
], 'content->usps')
```

**Comment by disitec** [comment]
Hey @jeffreydevreede sorry about the delay. It seems to be related with this issue #58 

parent::resolve is not being executed and this line 

`$value = data_get($resource, str_replace('->', '.', $attribute), '___missing');`

which is doing the magic you need is not being reached.

I would need either a bit more time to fix this or a helpful PR coming.
