### ISSUE TITLE
resolve and fill callbacks broken for row

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-fields#58]
Maybe I'm missing something but the resolveUsing code doesn't even get hit at all? On version 0.6.1.

Adding a `dd` into the resolveUsing callback is never called. In fact adding a dd to either the row or the inner row fields seem to do nothing.

Snippet as an example:

           Row::make('Features and Benefits', [
                Text::make('test', null, function($feature) {
                    dd('test');
                }),
                Textarea::make('Feature/Benefit', 'feature', function ($feature) {
                    dd('test');
                    return $feature;
                })->hideLabelInForms()
            ], 'features')

Granted I'm trying to do something like a list where the result is just an array of strings, but the logic should still be getting hit.

ADDITIONAL UPDATE: It also broke using a resolveUsing on the Row field itself. reverting back to 0.6.0 makes the row field level resolve work again

ADDITIONAL ADDITIONAL UPDATE:
Snippet for example of Row level resolve/fil working in 0.6.0 but broken completely in 0.6.1

            Row::make('Features and Benefits', [
                Textarea::make('Feature/Benefit', 'feature')->hideLabelInForms()
            ], 'features', function ($features) {
                return collect($features)->map(function ($feature) {
                    return ['feature' => $feature];
                });
            })->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                if ($request->exists($requestAttribute)) {
                    // Ensure we don't store that random row_id that gets generated
                    $model->{$attribute} = collect($request[$requestAttribute])->pluck('feature')->flatten()->filter();
                }
            })->fieldClasses('w-full px-8 py-6')->hideHeading()->addRowText('Add Feature'),

I know this kind of logic isn't quite in line with how it's supposed to work, but still a very breaking change based on how fields are supposed to work in Nova.
Also noting that using the more general syntax of calling `resolveUsing` on the Row field also doesn't work as expected.

I figured this level of breakage deserves it's own issue rather than just piggy backing on an old closed issue #49)

**Comment by disitec** [comment]
Thanks for the report. I will take a deep look into this

**Comment by disitec** [comment]
Yeah. Looks like this method, added in a previous PR, overrides the resolve method and something is breaking the chain.
https://github.com/64robots/nova-fields/blob/master/src/Row.php#L101

I've opened this issue #67 We need a test suite for avoiding this in the future.

Still investigating this issue.

**Comment by ragingdave** [comment]
I had a random thought that might be worth looking into as well, potentially just merging the logic of the JSON field and the Row field since both need to do the exact same thing....just one sets the value as an array of objects and the other as just an object. Even then potentially the casting could be handled via the in-model cast configuration so the actual setting of the value from either the Row or JSON field doesn't even need to worry about array or just object.

**Comment by disitec** [comment]
Fixed in 0.7.2
