### ISSUE TITLE
Image field support

### ISSUE THREAD

**Issue by jianminLee** [64robots/nova-fields#6]
Thank you for your package, he is very good.
But he does not currently support Image fields， I use the Text field instead, then the text content is too long, the interface is messy；
look this:
![_20180926154551](https://user-images.githubusercontent.com/13827117/46064929-52560800-c1a3-11e8-8b61-738a489a0e03.png)

**Comment by disitec** [comment]
We have plans to include all fields. In the mean time you could use the Nova\Fields\Image

**Comment by jianminLee** [comment]
@disitec 
I tried to use Nova \ Fields \ Image, but it was very ugly

**Comment by jianminLee** [comment]
@disitec 
![image](https://user-images.githubusercontent.com/13827117/46071522-ca77fa00-c1b2-11e8-85bd-156bda13f239.png)
this image field is null

**Comment by jianminLee** [comment]
@disitec 
![image](https://user-images.githubusercontent.com/13827117/46072187-5179a200-c1b4-11e8-8678-39b0a6fbd887.png)
![image](https://user-images.githubusercontent.com/13827117/46072201-5c343700-c1b4-11e8-93df-ff67dd4101c2.png)
It seems that there are still some problems, and the Image field cannot upload the image file.
