### ISSUE TITLE
element.handleChange error with belongsTo in row

### ISSUE THREAD

**Issue by emiliogrv** [64robots/nova-fields#61]
Hi, when I try update a resource with a BelongsTo field into row, row issued and error

![1](https://user-images.githubusercontent.com/13983577/51069961-9fa19c80-160f-11e9-8d04-c1d0d5062b7b.png)

**UPDATE**
Steps to reproduce it:

Example: 
An invoices previusly created with lines (products => lines/invoices details)

If try edit it, the Row component throw an error, can see it in the image above

**Comment by disitec** [comment]
Fixed in 0.6.3
