### ISSUE TITLE
JSON Field: No nova functions are working

### ISSUE THREAD

**Issue by bernhardh** [64robots/nova-fields#7]
If you try to use common nova functions on fields inside a json-field, it is not working. For example:

```php
\R64\NovaFields\JSON::make('Address', [   
    // Is showing on update screen
    Text::make("City", 'city')->hideWhenUpdating(),
    
     // Is showing on detail screen
    Text::make('Postal Code', "zip")->hideFromDetail()
], 'json_data'),
```

**Comment by ragingdave** [comment]
While this is most likely doable for most the common methods, the one that seems very difficult would be if someone were to hide a field from the form. Any suggestion on how that should work? Perhaps changing thesvae logic to merge the Jon already saved with the changes? But if you remove a field that won't clean up the already saved json

**Comment by bernhardh** [comment]
You made a very good point to think about these side effects. Hiding on detail or on create shouldn't be a problem. 

From a "user" perspective, it should work exactly like it does with the other field. "Hidden" fields (hideWhenUpdating) keep the same value as they have (since they aren't touched at all in "normal" fields). So I think this should also work for json fields. 

How to implement this? Maybe merge the posted object with the filtered original object before save. "Filtered original object" means, to only get the properties of hideFromUpdate Fields.

**Comment by disitec** [comment]
I think we could do soport for this in JSON and Row field. But as @ragingdave said If we remove a Json subfield only when updating, this field is going to be deleted from the original json. We have to find a way to keep it in the structure. Maybe a v-show=false or a hidden field.

**Comment by bernhardh** [comment]
Yes. Hiding it only from the markup is a good solution. So no php merge/change has to be done

**Comment by disitec** [comment]
You can now use the following methods with Json and Row subfields:

* hideFromDetail
* hideWhenCreating
* hideWhenUpdating
* onlyOnDetail
* onlyOnForms
* exceptOnForms

Added in 0.3.1
