### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by thanoseleftherakos** [64robots/nova-fields#70]
Congratulations for the great job!

Does nova-fields support multi language fields?
Im using spatie/laravel-translatable together with mrmonat/nova-translatable.

The JSON fields that Im testing are saving correctly on the database but when I try to edit the fields again from the resource model page are empty.
Here what I see on the database (which is correct) after saving:
{"en":{"name":"En Name","description":"En desc"},"el":{"name":"EL name","description":"EL desc"}}

**Comment by disitec** [comment]
I think this is another case for nested JSON support. #14

This is a planned feature. Feel free to open a PR with your case and I will happy to review it.

**Comment by ipitchkhadze** [comment]
For spaie/laravel-translatable you can do like this:

```php
$this->fields->each(function ($field) use ($request, $model, $attribute) {
            if($field->component === 'translatable') {
                $tr = [];
                collect($field->meta['locales'])->each(function ($language,$lang) use (&$tr,$field,$request, $model, $attribute) {
                    $tr[$field->attribute][$lang] = $request[$attribute . '.' . $field->attribute.'.'.$lang];
                });
                $model->{$attribute}= array_merge($model->{$attribute}, $tr);
            } else {
                $field->fillInto($request, $model, $attribute . '->' . $field->attribute, $attribute . '.' . $field->attribute);
            }
        });
```
