### ISSUE TITLE
Enable JSON fields with collection cast instead of object cast

### ISSUE THREAD

**Issue by tpetry** [64robots/nova-fields#72]
Currently, the JSON field is forcing the use of an object cast in eloquent for each field that should be editable with the Json field. Since most applications were written before the release of Nova, there are many applications that decided to use the Collection Cast in Eloquent. The JSON field can therefore not be used without rewriting many parts of the source code.

A configuration option if you want to use object or collection Casts for the JSON field would be very useful.

**Comment by tpetry** [comment]
According to my tests the note in the information is incorrect? In my tests a json field on a collection-cast works correctly.

**Comment by disitec** [comment]
Hey @tpetry sorry for the delay can you explain a bit more your case showing a reproduction to take a look into?

thanks!

**Comment by tpetry** [comment]
There is no problem ;)

Your documentation is stating `In this example ensure that the content_json field is being set to cast to object on the underlying model instance.` Which implies that json fields need to be set to `object` cast. But many applications are using `collection` cast which (by the documentation) should not work. But you can use either `object` or `collection` cast. So it's simply a documentation "bug".
