### ISSUE TITLE
Unused horizontal space in json field

### ISSUE THREAD

**Issue by tpetry** [64robots/nova-fields#73]
As you can see on the screenshot, the JSON field does not fit visually to the rest of the core nova elements:
* The label of each json field should be more left to be at the same vertical line like the text field above (removing padding-left)  
* The input field of each field should be more right to be at the same vertical line like the input field above (remove `padding-right`)  
* Additionally the space for the label is too small for longer words. The space gained by removing the upper whitespace could be used to double the space of the label.

<img width="1387" alt="bildschirmfoto 2019-02-14 um 17 12 31" src="https://user-images.githubusercontent.com/315686/52800328-d25e0b00-307b-11e9-95d3-904221070cb0.png">

**Comment by robmpreston** [comment]
The layout is completely customizable on all of our fields. Here's an example of one we do in our apps:
```
JSON::make('Content', $this->contentFields(), 'content_field')
                ->hideLabelInDetail()
                ->hideLabelInForms()
                ->hideWhenUpdating()
                ->fieldClasses('w-full')
                ->panelFieldClasses('w-full'),
```

```
    public function contentFields()
    {
        return [
            Trix::make('Content'),
            Select::make('Form Alignment')->options([
                'left' => 'Left',
                'right' => 'Right',
                'center' => 'Center',
            ]),
            Number::make('Multiplier')
                ->min(1)
                ->max(10)
                ->step(1),
            Textarea::make('Impact Content'),
            Boolean::make('Allow monthly payments'),
            Textarea::make('Did you know'),
            Textarea::make('Donation confirmation'),
            Row::make('Amount values', [
                Text::make('Label')
                  ->fieldClasses('w-full px-8 py-6')
                  ->hideLabelInForms(),
                Text::make('Numeric value')
                  ->fieldClasses('w-full px-8 py-6')
                  ->hideLabelInForms(),
              ])
        ];
    }
```

This results in a layout that looks like this:
<img width="1587" alt="screen shot 2019-02-14 at 2 07 07 pm" src="https://user-images.githubusercontent.com/9950092/52811083-38d62f80-3062-11e9-8539-17cba828214d.png">

So you wouldn't even know it was a JSON field unless you looked at the code. We need to get some better documentation to cover this, but yeah, it's not too hard to customize to your liking.
