### ISSUE TITLE
JSON deos not support the flag JSON_NUMERIC_CHECK

### ISSUE THREAD

**Issue by faizaajmal** [64robots/nova-fields#74]
the json converts number into strings. i only want to store the amount as number in my json string like that 
**Required: Result :** {"amount": 500, "currency": "SEK"} but it save the number with double quotes 
 {"amount": "500", "currency": "SEK"}

JSON::make('Price', [
                Number::make('Amount'),
                Text::make('Currency'),
            ])

**Comment by disitec** [comment]
Hi. Sorry for the delay.

You can use `fillUsing` to modify your request before saving

```php
JSON::make('Price', [
   Number::make('Amount'),
   Text::make('Currency'),
])->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
    $value = $request[$requestAttribute];
    $model->{$attribute} = json_encode($value, JSON_NUMERIC_CHECK);
})```
