### ISSUE TITLE
Why BelongsTo does not work in Row::404

### ISSUE THREAD

**Issue by BenySLO** [64robots/nova-fields#75]
`

			BelongsTo::make('Plane Type', 'planeTypes'),
			Row::make('flight_type_price', [
				BelongsTo::make('Plane Type', 'planeTypes')->fieldClasses('w-full px-8 py-6')
					->hideLabelInForms(),
			])->fieldClasses('w-full px-8 py-6')
			   ->labelClasses('w-1/9 px-8 py-6'),`

I've tryed to create one outside of my Row:: and it works just fine but the BleongsTo:: inside my Row:: does not work properly. I get status code 404 in my browser. If anyone knows why?

**Comment by BenySLO** [comment]
i might add this is the message i get

> vendor.js?id=52886433f04b87b2c184:1 GET http://localhost:3000/nova-r64-api/flight_type_prices/associatable/planeTypes?first=false&search=&withTrashed=false 404 (Not Found)

**Comment by disitec** [comment]
BelongsTo field uses the row attribute for fetching the associatable items.

i.e
```
Row::make('product', [
			BelongsTo::make('Category, 'categories'),
		])``

would generate `http://localhost:3000/nova-r64-api/products/associatable/categories`

Could you name your row field like a field that has actual relation with planeTypes?

**Comment by BenySLO** [comment]
i mean does the naming matter, its just a test scenario so i see if it loads, I load from this function in my model: 
`public function planeTypes() {
		return $this->belongsTo(PlaneType::class, 'flight_type_price');
	}`
and the table row in my DB is 'flight_type_price' but the point is the belongs to wont show options from my PlaneType class but if i use it outside of row it works as expected.

**Comment by disitec** [comment]
Your row field has to be named as your main model and BelongsTo field has to be named like the relation.

```php
Row::make('product', [
    BelongsTo::make('Category, 'categories'),
])```

**Comment by midorikocak** [comment]
Is there any updates on this?
