### ISSUE TITLE
Saving Row filed into hasMany relationship

### ISSUE THREAD

**Issue by phuclh** [64robots/nova-fields#76]
I have 2 models: Attribute and AttributeOption (A attribute has many options)
and 2 tables (attributes and attribute_options)

When I save the attribute model, how can I save the Row field to the related table (attribute_options)

Here is my code:

```
       Row::make('Add options', array(
                            Text2::make('Name')
                                ->fieldClasses('w-full px-8 py-6')
                                ->hideLabelInForms(),
                            Number::make('Position')
                                ->fieldClasses('w-full px-8 py-6')
                                ->withMeta(['value' => 1])
                                ->hideLabelInForms(),
                        ), 'options')
```

Currently, when I submit the form, it will try to save the Row field (options) into the `attributes` table, not `attribute_options` table.

Thank you for your help!!!!

**Comment by phuclh** [comment]
Can anybody help me???

**Comment by disitec** [comment]
Hi, sorry for the delay.

You can use `fillUsing` to modify the request before save.

```php
->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                unset($model->attribute); // avoid storing value in the parent model
                foreach( $request[$requestAttribute] as $row) {
                    // Perform operation with each row
                }
            }),
```

In your case this could have a caveat as you dont know the option_id in that scope. In that case you would need to create an Observer for that model and store the relation in the `created` hook.

```php
public function created(Option $option)
    {
        $options = request()->options);
        foreach ($options as $option) {
            // whatever
        }
    }
```
